#!/usr/bin/env bash

# Beende das Skript, sobald ein Fehler bei einem Kommando auftritt
set -e
set -o pipefail

# Überprüfe, ob alle notwendigen Tools zur Verfügung stehen
for tool in git make rsync
do
    command -v $tool >/dev/null 2>&1 \
        || { echo >&2 "\"$tool\" nicht installiert. Abbruch"; exit 1; }
done

# Benutzerabfragen
echo -e "Freifunk Firmware Tool\n"
echo -e "Community Wählen:\n"
echo -e "[t]roisdorf, [h]ennef, [sa]nkt Augustin, [l]ohmar, [n]iederkassel, [si]egburg, [r]heinbach, [w]achtberg:"
read input_community
echo -e "Firmware [b]auen, [s]ignieren oder s[y]nc:"
read input_feature

# Wenn "cleaning" ausgewählt wurde, können Eingaben zu Branch und Version
# ignoriert werden. Setze dazu diese Werte auf "save values". Bei allen
# anderen Tasks/Features wird der User nach den Eingaben gefragt.
if [ "$input_feature" == "s" ]; then
    echo -e "ranch auswählen: [s]table, [b]eta, [e]xperimental, e[v]ent, [f]utro"
    read input_branch
fi
if [ "$input_feature" == "b" ]; then
    echo -e "Branch auswählen: [s]table, [b]eta, [e]xperimental, e[v]ent, [f]utro"
    read input_branch
    echo -e "Neue Versionsnummer? (Nur für Bauen nötig)"
    read input_version
fi
if [ "$input_feature" == "y" ]; then
    input_branch=s
fi

# Wenn "freigeben" ausgewählt wurde, den User fragen, ob rsync mit der
# Option --dry-run ausgeführt werden soll. Das kann für Tests sinnvoll
# sein, wenn ein Kopieren der Firmware-Dateien nicht tatsächlich
# erfolgen soll.
rsync_opt="-aP --delete" # default rsync options
if [ "$input_feature" == "f" ]; then
    echo -e "Rsync mit Option --dry-run zu Testzwecken ausführen [j/n]?"
    read input_dryrun
    if [ "$input_dryrun" == "j" ]; then
        rsync_opt="$rsync_opt --dry-run"
    fi
fi

# Bedingungen setzen
case $input_community in
    troisdorf*|t*)
        community=troisdorf
        gluon_pfad=/home/gluon/gluon-troisdorf/
        firmware_pfad=/home/gluon/firmware/troisdorf/
        site_code=tdf;;
    hennef*|h*)
        community=hennef
        gluon_pfad=/home/gluon/gluon-hennef/
        site_code=Hennef
        firmware_pfad=/home/gluon/firmware/hennef/;;
    lohmar*|l*)
        community=lohmar
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=lo
        firmware_pfad=/home/gluon/firmware/lohmar/;;
    sanktaugustin*|sa*)
        community=sanktaugustin
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=sa
        firmware_pfad=/home/gluon/firmware/sanktaugustin/;;
    niederkassel*|n*)
        community=niederkassel
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=ndk
        firmware_pfad=/home/gluon/firmware/niederkassel/;;
    siegburg*|si*)
        community=siegburg
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=su
        firmware_pfad=/home/gluon/firmware/siegburg/;;
    rheinbach*|r*)
        community=rheinbach
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=su
        firmware_pfad=/home/gluon/firmware/rheinbach/;;
     wachtberg*|w*)
        community=wachtberg
        gluon_pfad=/home/gluon/gluon-rsk/
        site_code=su
        firmware_pfad=/home/gluon/firmware/wachtberg/;;
    *)
        echo "Keine gültige Auswahl für Community!"
        exit 1;;
esac

case $input_branch in
    stable*|s*)
        gluon_version=v2015.1.2
        site_version=v2015.1
        gluon_version_name=2015.1.2
        branch=stable
        gluon_options=""
        branch_name=stable;;
    beta*|b*)
        gluon_version=v2015.1.2
        site_version=v2015.1
        gluon_version_name=2015.1.2
        branch=beta
        gluon_options=""
        branch_name=beta;;
    experimental*|e*)
        gluon_version=v2015.1.2
        site_version=v2015.1
        gluon_version_name=v2015.1.2
        branch=experimental
        gluon_options="BROKEN=1"
        branch_name=exp;;
    event*|v*)
        gluon_version=v2015.1.2
        site_version=event
        gluon_version_name=v2015.1.2
        branch=event
        gluon_options="BROKEN=1"
        branch_name=event;;
    futro*|f*)
        gluon_version=v2015.1.2
        site_version=futro
        gluon_version_name=v2015.1.2
        branch=futro
        gluon_options="BROKEN=1"
        branch_name=futro;;
    *)
        echo "Keine gültige Auswahl für Branch!"
        exit 1;;
esac

# Task/Feature ausführen
case $input_feature in

    #### Firmware bauen ####
    bauen*|b*)
        echo "Berechtigung wird geprüft"
        if [ "$USER" != "gluon" ]; then
            echo "Der Benutzer $USER ist nicht berechtigt, die Firmware zu bauen!" 
            exit 1
        else
            echo "User Gluon erkannt!"
        fi
        echo -e "Gluon und Site Configuration Updaten? [j/n]"
        read update
        case $update in
            j*)
                echo -e "Repositorys werden Aktualisiert"
                #Update Gluon
                cd $gluon_pfad
                git checkout $gluon_version
                git pull origin $gluon_version
                #Update Site.conf
                if [ "$gluon_pfad" = "/home/gluon/gluon-rsk/" ]; then
                	cd "$gluon_pfad""site"
                	git checkout $community-$site_version
                	git pull origin $community-$site_version
                else
                cd "$gluon_pfad""site"
                git checkout $site_version
                git pull origin $site_version
            fi;;
            n*)
                echo -e "Es werden keine Updates eingespielt!";;
        esac
        cd $gluon_pfad
        #Firmware Bauen
        make update
        if [[ "$input_branch" = "futro"]]; then
        	make -j5 GLUON_BRANCH=$branch GLUON_TARGET=x86-generic DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
        else
        make -j5 GLUON_BRANCH=$branch GLUON_TARGET=ar71xx-generic DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
        make -j5 GLUON_BRANCH=$branch GLUON_TARGET=ar71xx-nand DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
        make -j5 GLUON_BRANCH=$branch GLUON_TARGET=mpc85xx-generic DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
        make -j5 GLUON_BRANCH=$branch GLUON_TARGET=x86-generic DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
        make -j5 GLUON_BRANCH=$branch GLUON_TARGET=x86-kvm_guest DEFAULT_GLUON_RELEASE=$gluon_version_name-$branch_name-$input_version $gluon_options
    	fi;;
        make manifest GLUON_BRANCH=$branch
        #Firmware Images Kopieren
        rm -rf "$firmware_pfad""$branch"
        cp -r "$gluon_pfad"images "$firmware_pfad""$branch"
        rm -rf "$gluon_pfad"images
        cd "$firmware_pfad""$branch"/factory/
        #x86 Images Zippen
        zip x86_images-$gluon_version_name-$branch_name-$input_version.zip *.img *.img.gz *.vdi *.vmdk
        chmod 775 -R "$firmware_pfad""$branch"/
        if [ $community = troisdorf ]; then
        echo -e "Aktuelle Firmware in github taggen? [j/n]"
        read tag
        case $tag in
            j*)
                echo -e "Tag $branch-$input_version wird erstellt."
                #Tagging Gluon
                cd $gluon_pfad
                git tag $gluon_version_name-$branch-$input_version
                git push origin --tags
                #Tagging Site
                cd "$gluon_pfad"site
                git tag $gluon_version_name-$branch-$input_version
                git push origin --tags
                #Tagging Build-Script
                cd /home/gluon
                git tag $gluon_version_name-$branch-$input_version
                git push origin --tags;;
            n*)
                echo -e "Es wurden keine Tags erstellt!"
                echo -e "Firmware im Branch: $branch wurde in Version $input_version gebaut.";;
        esac
        /home/gluon/slackbot_build_$branch.sh
    	fi;;
    	
    
    #### Firmware signieren ####
    signieren*|s*)
        "$gluon_pfad"contrib/sign.sh ~/firmwarekey "$firmware_pfad""$branch"/sysupgrade/"$branch".manifest
        echo -e "Die Firmware aus dem Branch $branch wurde erfolgreich signiert!"
        if [ $community = troisdorf ]; then
        /home/gluon/slackbot_signed_$branch.sh
        fi;;

    #### Syncronisieren ####
    sync*|y*)
        if [ "$USER" != "gluon" ]; then
            echo "Keine Berechtigung" 
            exit 1
        else
            echo "User Gluon erkannt!"
        fi
        
            rsync $rsync_opt /home/gluon/firmware/ root@10.0.0.75:/var/www/firmware
            rsync $rsync_opt -e "ssh -p 2222" /home/gluon/firmware/ fwupload@46.4.138.183:/srv/fwuploads
            rsync $rsync_opt /home/gluon/firmware/troisdorf/ fwupload@update2.infra.fftdf:~/www
            ;;              
	esac

echo -e "Alle Befehle ausgeführt!"
